name: CI One

on:
  merge_group:
  pull_request:
  workflow_dispatch:

jobs:
  ci-one-job-one:
    if: ${{ github.event_name == 'merge_group' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Done"
